import { Montserrat, Open_Sans, Righteous } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const righteous = Righteous({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-righteous",
});

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "600"],
  variable: "--font-open-sans",
});

export const metadata = {
  title: "FullStack-dev-portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <body
  className={`
    ${righteous.variable}
    antialiased
    text-white
    bg-[url('/assets/bg-full.jpg')]
    bg-cover
    bg-center
    bg-fixed
    min-h-screen
  `}
>
  <Navbar />
  
  {children}
</body>
    </html>
  );
}
